## question 1

In [2]:
import numpy as np

In [3]:
a=np.random.random([10,1])


In [4]:
print (a)

[[0.17024381]
 [0.57103322]
 [0.57545151]
 [0.31855624]
 [0.03886387]
 [0.14854413]
 [0.93773232]
 [0.18162421]
 [0.49780241]
 [0.68610047]]


In [5]:
np.mean(a)

0.412595219354604

## question 2


In [6]:
b=np.random.random([20,1])

In [7]:
print (b)

[[0.32843753]
 [0.76878979]
 [0.17835635]
 [0.11322107]
 [0.87113677]
 [0.8357492 ]
 [0.72744446]
 [0.53685546]
 [0.05084964]
 [0.11890432]
 [0.34159288]
 [0.96115565]
 [0.01267835]
 [0.33588094]
 [0.69681622]
 [0.35397818]
 [0.91739845]
 [0.7118612 ]
 [0.70323231]
 [0.34508867]]


In [8]:
np.var(b)

0.09257473330594748

In [9]:
np.std(b)

0.3042609625074296

## question 3

In [17]:
c=np.random.random([10,20])

In [13]:
d=np.random.random([20,25])

In [15]:
e=np.dot(c,d)

In [48]:
print (e)

[[5.04561954 3.60915066 4.12717162 5.08747076 4.3830975  3.84151058
  3.84903688 4.23060251 4.85646525 5.45351955 4.12996559 4.58125683
  4.5263062  4.5387415  4.46313363 4.1486004  4.66923285 4.3586141
  3.98515013 4.84683739 4.13865503 4.59997463 4.77298284 4.79780062
  4.28578554]
 [5.41304963 4.17080992 4.39590114 5.53744905 6.47119702 3.81401534
  4.27324494 4.01040149 6.38705519 5.97117425 5.78537382 4.88923392
  4.98886971 5.12921324 5.9268805  4.65171464 4.95521416 5.00532994
  5.05518048 5.63348874 5.00094071 4.46430872 5.2094324  4.96677125
  5.26867906]
 [5.994131   4.80514058 4.98996137 7.07114356 6.38731162 4.8898542
  4.77249129 6.0442974  5.70721518 7.0930961  6.41115499 6.86295888
  6.51335253 6.33287992 6.12614362 5.63589218 6.32397976 5.76798583
  5.76985749 5.64575155 5.81149547 6.08585625 5.38458889 4.58391977
  6.1149704 ]
 [4.26440259 3.21445369 4.40144978 4.75461697 4.44470513 3.65557142
  2.91136694 3.4985202  4.03628172 4.6231187  3.31265308 3.89333499
  4.9949

In [36]:
e.shape

(10, 25)

In [37]:
np.sum(e)
      

1253.0430011395274

## question 4

In [38]:
import numpy as np

In [39]:
w = np.arange(10).reshape(10,1)

In [40]:
def myfunc(x,axis):
    return 1/(1+ np.exp(-x))

In [41]:
np.apply_over_axes(myfunc,w,1)

array([[0.5       ],
       [0.73105858],
       [0.88079708],
       [0.95257413],
       [0.98201379],
       [0.99330715],
       [0.99752738],
       [0.99908895],
       [0.99966465],
       [0.99987661]])